#noload
import crafttweaker.api.block.Block;

println("Setting PMMO Mining XP");

val deepslateMulti = 1.3f;
val vanillaOres as float[string] = {
    "coal_ore": 40.0f,
    "copper_ore": 80.0f,
    "iron_ore": 100.0f,
    "lapis_ore": 120.0f,
    "redstone_ore": 120.0f,
    "gold_ore": 200.0f,
    "emerald_ore": 300.0f,
    "diamond_ore": 600.0f,
};

for resourceName, xpAward in vanillaOres {
    setMiningXpAward(<block:minecraft:${resourceName}>, xpAward);
    setMiningXpAward(<block:minecraft:deepslate_${resourceName}>, xpAward * deepslateMulti);
}

val rare as float = 60.0f;
val uncommon as float = 30.0f;

val manualMap as float[string] = {
    "minecraft:obsidian": 120.0f,
    "minecraft:crying_obsidian": 200.0f,
    "minecraft:ancient_debris": 2000.0f,
    "irons_spellbooks:arcane_debris": 2000.0f,
    "minecraft:nether_quartz_ore": 30.0f,
    "minecraft:nether_gold_ore": 50.0f,
    "create:zinc_ore": 150.0f,
    "create:deepslate_zinc_ore": 120.0f * deepslateMulti,
    "alexscaves:coprolith_coal_ore": 50.0f * deepslateMulti,
    "alexscaves:galena_iron_ore": 100.0f * deepslateMulti,
    "alexscaves:guanostone_redstone_ore": 150.0f * deepslateMulti,
    "alexscaves:radrock_uranium_ore": 600.0f,
    "minecraft:bone_block": rare,
    "minecraft:magma_block": uncommon,
    "minecraft:prismarine": rare,
    "alexscaves:acidic_radrock": rare,
    "alexsmobs:capsid": rare,
    "minecraft:budding_amethyst": rare,
    "minecraft:amethyst_block": rare,
    "minecraft:fire_coral_block": rare,
    "minecraft:horn_coral_block": rare,
    "minecraft:bubble_coral_block": rare,
    "minecraft:dead_tube_coral_block": rare,
    "minecraft:dead_horn_coral_block": rare,
    "minecraft:dead_fire_coral_block": rare,
    "minecraft:brain_coral_block": rare,
    "minecraft:dead_brain_coral_block": rare,
    "minecraft:tube_coral_block": rare,
    "minecraft:dead_bubble_coral_block": rare,
    "twilightforest:bold_stone_pillar": uncommon,
    "twilightforest:giant_cobblestone": uncommon,
    "twilightforest:nagastone_pillar": uncommon,
    "twilightforest:nagastone": uncommon,
    "twilightforest:twisted_stone": uncommon,
    "twilightforest:mossy_etched_nagastone": uncommon,
    "twilightforest:mazestone_brick": uncommon,
    "twilightforest:twisted_stone_pillar": uncommon,
    "twilightforest:mazestone_border": uncommon,
    "twilightforest:etched_nagastone": uncommon,
    "twilightforest:cut_mazestone": uncommon,
    "twilightforest:mossy_nagastone_pillar": uncommon,
    "twilightforest:nagastone_head": uncommon,
    "twilightforest:decorative_mazestone": uncommon,
    "twilightforest:cracked_mazestone": uncommon,
    "twilightforest:mazestone_mosaic": uncommon,
    "twilightforest:mossy_mazestone": uncommon,
    "twilightforest:mazestone": uncommon,
    "twilightforest:cracked_etched_nagastone": uncommon,
    "twilightforest:cracked_nagastone_pillar": uncommon,
    "alexscaves:guanostone_bricks": uncommon,
    "alexscaves:smooth_limestone": uncommon,
    "alexscaves:guanostone": uncommon,
    "alexscaves:guanostone_chiseled": uncommon,
    "alexscaves:limestone": uncommon,
    "alexscaves:limestone_chiseled": uncommon,
    "alexscaves:limestone_pillar": uncommon,
    "alexscaves:sulfur": uncommon,
    "alexscaves:abyssmarine": uncommon,
    "alexscaves:radrock": uncommon,
    "alexscaves:smooth_bone": uncommon,
    "alexscaves:coprolith": uncommon,
    "alexscaves:porous_coprolith": rare,
    "alexscaves:peering_coprolith": rare,
    "create:ochrum": uncommon,
    "create:limestone": uncommon,
    "create:crimsite": uncommon,
    "create:asurine": uncommon,
    "create:scoria": uncommon,
    "create:scorchia": uncommon,
    "create:veridium": uncommon,
    "minecraft:andesite": uncommon,
    "minecraft:diorite": uncommon,
    "minecraft:basalt": uncommon,
    "minecraft:smooth_basalt": uncommon,
    "minecraft:calcite": uncommon,      
    "minecraft:bricks": uncommon,      
    "minecraft:chiseled_red_sandstone": uncommon,
    "minecraft:smooth_sandstone": uncommon,
    "minecraft:polished_blackstone": uncommon,
    "minecraft:chiseled_stone_bricks": uncommon,
    "minecraft:end_stone": uncommon,
    "minecraft:infested_cracked_stone_bricks": uncommon,
    "minecraft:smooth_red_sandstone": uncommon,
    "minecraft:infested_chiseled_stone_bricks": uncommon,
    "minecraft:infested_cobblestone": uncommon,
    "minecraft:chiseled_polished_blackstone": uncommon,
    "minecraft:infested_mossy_stone_bricks": uncommon,
    "minecraft:chiseled_sandstone": uncommon,
    "minecraft:mossy_stone_bricks": uncommon,
    "minecraft:cut_sandstone": uncommon,
    "minecraft:gilded_blackstone": uncommon,
    "minecraft:lodestone": uncommon,
    "minecraft:infested_stone_bricks": uncommon,
    "minecraft:cobbled_deepslate": uncommon,
    "minecraft:end_stone_bricks": uncommon,
    "minecraft:blackstone": uncommon,
    "minecraft:red_sandstone": uncommon,
    "minecraft:cut_red_sandstone": uncommon,
    "minecraft:pointed_dripstone": uncommon,
    "minecraft:mossy_cobblestone": uncommon,
    "minecraft:dripstone_block": uncommon,
    "minecraft:polished_blackstone_bricks": uncommon,
    "minecraft:cracked_polished_blackstone_bricks": uncommon,
    "minecraft:infested_stone": uncommon,
    "minecraft:infested_deepslate": uncommon,
    "minecraft:sandstone": uncommon,
    "minecraft:smooth_stone": uncommon,
    "minecraft:cracked_stone_bricks": uncommon,
    "minecraft:stone_bricks": uncommon,
    "minecraft:glowstone": uncommon,
    "minecraft:deepslate": uncommon,
    "minecraft:granite": uncommon,
    "minecraft:nether_bricks": uncommon,
    "minecraft:tuff": uncommon,
    "minecraft:packed_ice": uncommon,
    "minecraft:blue_ice": uncommon,
    "minecraft:gray_terracotta": uncommon,
    "minecraft:red_glazed_terracotta": uncommon,
    "minecraft:pink_terracotta": uncommon,
    "minecraft:white_terracotta": uncommon,
    "minecraft:red_terracotta": uncommon,
    "minecraft:brown_terracotta": uncommon,
    "minecraft:blue_terracotta": uncommon,
    "minecraft:magenta_glazed_terracotta": uncommon,
    "minecraft:green_terracotta": uncommon,
    "minecraft:brown_glazed_terracotta": uncommon,
    "minecraft:light_gray_glazed_terracotta": uncommon,
    "minecraft:orange_glazed_terracotta": uncommon,
    "minecraft:purple_glazed_terracotta": uncommon,
    "minecraft:orange_terracotta": uncommon,
    "minecraft:yellow_terracotta": uncommon,
    "minecraft:yellow_glazed_terracotta": uncommon,
    "minecraft:gray_glazed_terracotta": uncommon,
    "minecraft:black_glazed_terracotta": uncommon,
    "minecraft:light_blue_terracotta": uncommon,
    "minecraft:light_gray_terracotta": uncommon,
    "minecraft:green_glazed_terracotta": uncommon,
    "minecraft:magenta_terracotta": uncommon,
    "minecraft:pink_glazed_terracotta": uncommon,
    "minecraft:purple_terracotta": uncommon,
    "minecraft:blue_glazed_terracotta": uncommon,
    "minecraft:white_glazed_terracotta": uncommon,
    "minecraft:light_blue_glazed_terracotta": uncommon,
    "minecraft:cyan_terracotta": uncommon,
    "minecraft:lime_terracotta": uncommon,
    "minecraft:lime_glazed_terracotta": uncommon,
    "minecraft:terracotta": uncommon,
    "minecraft:cyan_glazed_terracotta": uncommon,
    "minecraft:black_terracotta": uncommon,
    "twilightforest:weathered_deadrock": uncommon,
    "twilightforest:deadrock": uncommon,
    "twilightforest:cracked_deadrock": uncommon,
    "minecraft:cobblestone": 4.0f,
    "minecraft:stone": 4.0f,
    "minecraft:netherrack": 4.0f,
    "minecraft:ice": 4.0f
};

for resourceName, xpAward in manualMap {
    setMiningXpAward(<block:${resourceName}>, xpAward);
}

function setMiningXpAward(block as Block, xpAward as float) as void {
    setBlockXP(block, <constant:pmmo:eventtype:block_break>, {"mining_group": (xpAward as long) as long?});
}
